theme: jekyll-theme-minimal
title: Saurin Parikh
logo: "/images/Headshot.jpg?raw=true"
description: >
  Physician-Engineer-Scientist
  <br>
  Problem Solver
  <br>
  <a href="https://www.linkedin.com/in/sauriiiin/" target="_blank">LinkedIn</a> &#124; <a href="https://github.com/sauriiiin" target="_blank">GitHub</a> &#124; <a href="mailto:saurinbp@gmail.com">Email</a>
  <br> 
  Download my resume <a href="https://sauriiiin.github.io/files/Saurin_Parikh_CV.pdf" target="_blank">here</a>.
include:
  - .htaccess
  - _pages
  - _layouts
  - _data
