theme: jekyll-theme-minimal
title: Saurin Parikh
logo: "/images/saurin.jpg?raw=true"
description: >
  Physician-Engineer-Scientist &#124; Problem Solver
  <br>
  <a href="https://www.linkedin.com/in/sauriiiin/" target="_blank">LinkedIn</a> &#124; <a href="https://twitter.com/sauriiiin" target="_blank">Twitter</a> &#124; <a href="https://github.com/sauriiiin" target="_blank">GitHub</a> &#124; <a href="mailto:sauriiiin@gmail.com">Email</a>
  <br> 
  Download my complete CV <a href="https://sauriiiin.github.io/files/CV_Saurin_Parikh.pdf" target="_blank">here</a>.
include:
  - .htaccess
  - _pages
  - _layouts
  - _data
