theme: jekyll-theme-minimal
title: Saurin Parikh
logo: "/images/saurin.jpg?raw=true"
description: >
  Problem Solver
  <br>
  Doctor turned Engineer turned Scientist
  <br><br>
  <a href="https://www.linkedin.com/in/sauriiiin/">LinkedIn</a> &#124; <a href="https://twitter.com/sauriiiin">Twitter</a> | <a href="mailto:sauriiiin@gmail.com">Email</a>
