theme: jekyll-theme-minimal
title: Saurin Parikh
logo: "/images/saurin.jpg?raw=true"
description: >
  Problem Solver
  <br>
  <a href="https://github.com/sauriiiin" target="_blank">GitHub</a> &#124; <a href="https://www.linkedin.com/in/sauriiiin/" target="_blank">LinkedIn</a> &#124; <a href="https://twitter.com/sauriiiin" target="_blank">Twitter</a> &#124; <a href="mailto:sauriiiin@gmail.com">Email</a>
include:
  - .htaccess
  - _pages
  - _layouts
  - _data
